[workspace]
resolver = "3"
members = [
    "crates/editor",
    "crates/engine",
    "crates/macos_window",
]

[workspace.package]
version = "0.0.0"
authors = ["Tianjiao Nie"]
edition = "2024"

[workspace.dependencies]
bytemuck = "1"
egui = "0.33"
eframe = { version = "0.33", features = ["wgpu"] }
tokio = { version = "1", features = ["rt"] }
wgpu = "28"
winit = "0.30"
