[workspace]
resolver = "3"
members = [
    "crates/editor",
    "crates/engine",
]

[workspace.package]
version = "0.0.0"
authors = ["Tianjiao Nie"]
edition = "2024"

[workspace.dependencies]
bytemuck = "1.25.0"
egui = "0.33.3"
eframe = {
    version = "0.33.3",
    features = [
        "wgpu",
    ],
}
